---
- name: install docker
  yum: name={{item}} state=installed
  with_items:
   - yum-utils 
   - device-mapper-persistent-data 
   - lvm2 

- name: update docker config
  command: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker-ce 
  yum: name={{item}} state=installed
  with_items:
  - docker-ce*

- name: start docker service
  service: name=docker state=started

- name: enable docker 
  systemd:
   name: docker
   enabled: yes
   masked: no
#https://github.com/NaturalHistoryMuseum/scratchpads2/wiki/Install-Docker-and-Docker-Compose-(Centos-7)
